# Robot name goes here
mobile_robot: 
  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controller 1
  left_steer_controller: 
    type: effort_controllers/JointPositionController
    joint: front_left_wheel_shaft"
    pid : {p: 100.0 , i: 0.0 , d: 0.0} 

  right_steer_controller: 
    type: effort_controllers/JointPositionController
    joint: right_left_wheel_shaft"
    pid : {p: 100.0 , i: 0.0 , d: 0.0} 

  left_wheel_controller: 
    type: effort_controllers/JointVelocityController
    joint: front_left_wheel"
    pid : {p: 100.0 , i: 0.0 , d: 0.0} 

  right_wheel_controller: 
    type: effort_controllers/JointVelocityController
    joint: front_right_wheel"
    pid : {p: 100.0 , i: 0.0 , d: 0.0} 

  # Controller 2
  # Controller 3
  # ....
  # Controller n


 