mobile_robot: 
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # gazebo_ros_control:
  #   pid_gains:
  #     left_steer_controller:
  #       p: 20.0
  #       i: 0.01
  #       d: 1.0
  #     right_steer_controller:
  #       p: 20.0
  #       i: 0.01
  #       d: 1.0
  #     left_wheel_controller:
  #       p: 70.0
  #       i: 0.001
  #       d: 1.0
  #     right_wheel_controller:
  #       p: 70.0
  #       i: 0.001
  #       d: 1.0

  left_steer_controller: 
    type: effort_controllers/JointPositionController
    joint: front_right_shaft_joint
    pid : {p: 100.0 , i: 0.0 , d: 0.01} 

  right_steer_controller: 
    type: effort_controllers/JointPositionController
    joint: front_left_shaft_joint
    pid : {p: 100.0 , i: 0.0 , d: 0.0} 

  rear_wheel_controller: 
    type: velocity_controllers/JointVelocityController
    joint: rear_wheel_shaft_joint
    pid : {p: 100.0 , i: 0.0 , d: 0.0} 


 