controller_joint_names: ['', 'rear_left_wheel_shaft_joint', 'rear_right_wheel_shaft_joint', 'front_right_wheel_shaft_joint', 'front_right_wheel_joint', 'front_left_wheel_shaft_joint', 'front_left_wheel_joint', ]
